[project]
name = "dlsu-id-name-scraper"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "beautifulsoup4>=4.13.5",
  "requests>=2.32.5",
  "selenium>=4.35.0",
  "webdriver-manager>=4.0.2",
]
